In [9]:
from bokeh.sampledata.iris import flowers
flowers

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
from bokeh.sampledata.periodic_table import elements

In [10]:
elements.shape

(118, 21)

In [13]:
elements.isnull().sum()

atomic number                0
symbol                       0
name                         0
atomic mass                  0
CPK                          0
electronic configuration     0
electronegativity           21
atomic radius               47
ion radius                  26
van der Waals radius        80
IE-1                        16
EA                          33
standard state              19
bonding type                20
melting point               17
boiling point               24
density                     22
metal                        0
year discovered              0
group                        0
period                       0
dtype: int64

In [14]:
elements.dropna(inplace=True)

In [15]:
elements.isnull().sum()

atomic number               0
symbol                      0
name                        0
atomic mass                 0
CPK                         0
electronic configuration    0
electronegativity           0
atomic radius               0
ion radius                  0
van der Waals radius        0
IE-1                        0
EA                          0
standard state              0
bonding type                0
melting point               0
boiling point               0
density                     0
metal                       0
year discovered             0
group                       0
period                      0
dtype: int64

In [16]:
from bokeh.plotting import figure
from bokeh.io import output_file, show
from bokeh.models import Range1d, PanTool, ResetTool, HoverTool, ColumnDataSource, LabelSet

In [18]:
df= elements
df.columns

Index(['atomic number', 'symbol', 'name', 'atomic mass', 'CPK',
       'electronic configuration', 'electronegativity', 'atomic radius',
       'ion radius', 'van der Waals radius', 'IE-1', 'EA', 'standard state',
       'bonding type', 'melting point', 'boiling point', 'density', 'metal',
       'year discovered', 'group', 'period'],
      dtype='object')

In [21]:
df.head()

,atomic number,symbol,name,atomic mass,CPK,electronic configuration,electronegativity,atomic radius,ion radius,van der Waals radius,...,EA,standard state,bonding type,melting point,boiling point,density,metal,year discovered,group,period
2,3,Li,Lithium,6.941,#CC80FF,[He] 2s1,0.98,134.0,76 (+1),182.0,...,-60.0,solid,metallic,454.0,1615.0,0.54,alkali metal,1817,1,2
5,6,C,Carbon,12.0107,#909090,[He] 2s2 2p2,2.55,77.0,16 (+4),170.0,...,-154.0,solid,covalent network,3823.0,4300.0,2.26,nonmetal,Ancient,14,2
6,7,N,Nitrogen,14.0067,#3050F8,[He] 2s2 2p3,3.04,75.0,146 (-3),155.0,...,-7.0,gas,diatomic,63.0,77.0,0.00,nonmetal,1772,15,2
7,8,O,Oxygen,15.9994,#FF0D0D,[He] 2s2 2p4,3.44,73.0,140 (-2),152.0,...,-141.0,gas,diatomic,55.0,90.0,0.00,nonmetal,1774,16,2
8,9,F,Fluorine,18.9984032,#90E050,[He] 2s2 2p5,3.98,71.0,133 (-1),147.0,...,-328.0,gas,atomic,54.0,85.0,0.00,halogen,1670,17,2

In [29]:
from bokeh.plotting import figure
from bokeh.io import output_file, show
from bokeh.sampledata.periodic_table import elements
from bokeh.models import Range1d, PanTool, ResetTool, HoverTool, ColumnDataSource, LabelSet

colormap={'solid':'red','liquid':'orange','gas':'yellow'}
elements['color'] = [colormap[x] for x in elements['standard state']]
elements['size'] = elements['electronegativity'] * 8

solid = ColumnDataSource(elements[elements["standard state"]=="solid"])
liquid = ColumnDataSource(elements[elements["standard state"]=="liquid"])
gas = ColumnDataSource(elements[elements["standard state"]=="gas"])

#Define the output file path
output_file("elements.html")

#Create the figure object
f = figure()

#adding glyphs
f.circle(x="atomic radius", y="boiling point", size='size', fill_alpha=0.2, 
color="color", line_dash=[5,3], legend='Setosa', source=solid)

f.circle(x="atomic radius", y="boiling point", size='size', fill_alpha=0.2, 
color="color", line_dash=[5,3], legend='Versicolor', source=liquid)

f.circle(x="atomic radius", y="boiling point", size='size', fill_alpha=0.2,
color="color", line_dash=[5,3], legend='Virginica', source=gas)

#Save and show the figure
show(f)